spring:
  application:
    name: consumer-b-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group-b
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8092
